"""Stable typed reason codes for the deadline hero completion slice (#176)."""

from __future__ import annotations

from enum import StrEnum


class HeroErrorCode(StrEnum):
    """Deterministic reason a hero run sank to BLOCKED / FAILED."""

    UNVERIFIED_PACKAGE = "UNVERIFIED_PACKAGE"
    STALE_VERSION_BINDING = "STALE_VERSION_BINDING"
    RUN_BINDING_MISMATCH = "RUN_BINDING_MISMATCH"
    UNAUTHORIZED_TARGET = "UNAUTHORIZED_TARGET"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    UNSAFE_PAYLOAD = "UNSAFE_PAYLOAD"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    ACK_CORRELATION_MISMATCH = "ACK_CORRELATION_MISMATCH"
    ACK_SIGNATURE_INVALID = "ACK_SIGNATURE_INVALID"
    ACK_INVALID = "ACK_INVALID"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
