"""Stable typed reason codes for the bounded Gemini triage stage (#55)."""

from __future__ import annotations

from enum import StrEnum


class TriageErrorCode(StrEnum):
    """Deterministic machine-checkable reason a triage stage sank to BLOCKED/FAILED."""

    ENTRY_GATE_NOT_READY = "ENTRY_GATE_NOT_READY"
    MALFORMED_MODEL_OUTPUT = "MALFORMED_MODEL_OUTPUT"
    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"
    FORBIDDEN_SEMANTIC = "FORBIDDEN_SEMANTIC"
    INVALID_EVIDENCE_INTENT = "INVALID_EVIDENCE_INTENT"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    NO_APPROVED_EVIDENCE = "NO_APPROVED_EVIDENCE"
    EVIDENCE_RETRIEVAL_FAILED = "EVIDENCE_RETRIEVAL_FAILED"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_PROVIDER_FAILURE = "MODEL_PROVIDER_FAILURE"
    RATE_LIMIT = "RATE_LIMIT"
    MODEL_BUDGET_EXCEEDED = "MODEL_BUDGET_EXCEEDED"
