"""Stable machine-readable WHONET parser error codes (M2.2 / Issue #39)."""

from __future__ import annotations

from enum import StrEnum


class WhonetParserErrorCode(StrEnum):
    """Stable error codes emitted during WHONET-style CSV parsing and normalization."""

    EMPTY_CSV = "EMPTY_CSV"
    MISSING_REQUIRED_COLUMN = "MISSING_REQUIRED_COLUMN"
    DUPLICATE_COLUMN_HEADER = "DUPLICATE_COLUMN_HEADER"
    MALFORMED_CSV_ROW = "MALFORMED_CSV_ROW"
    MISSING_REQUIRED_VALUE = "MISSING_REQUIRED_VALUE"
    INVALID_ISOLATE_ID = "INVALID_ISOLATE_ID"
    INVALID_COLLECTION_DATE = "INVALID_COLLECTION_DATE"
    INVALID_TEXT_FIELD = "INVALID_TEXT_FIELD"
    INVALID_AST_COLUMN = "INVALID_AST_COLUMN"
    INVALID_AST_VALUE = "INVALID_AST_VALUE"
    EMPTY_AST_RESULTS = "EMPTY_AST_RESULTS"
    CANONICAL_VALIDATION_ERROR = "CANONICAL_VALIDATION_ERROR"
